# remote_theme: pmarsceill/just-the-docs
title: Third Reading
description: An exploration of ...
remote_theme: just-the-docs
search_enabled: true

# Custom Settings
color_scheme: supplementary

# LaTeX math equation support
use_math: true

# kramdown
kramdown:
  math_engine: mathjax
