# remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

# Settings
title: "Third Reading"
search_enabled: true

# Custom Settings
color_scheme: supplementary

# LaTeX math equation support
use_math: true

# kramdown
kramdown:
  math_engine: mathjax
