name: thirdreading
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - pytest>=7.4.*
  - coverage>=7.3.*
  - pylint>=2.17.*
  - pytest-cov>=4.1.*
  - flake8>=6.1.*
  - pip
  - pip:
      - sphinx
      - https://github.com/thirdreading/hub/raw/master/software/python/revitron-sphinx-theme-master.zip